version: '3'
services:
  axonserver:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - ./data:/data
  btc_mining_db:
    image: 'postgres'
    container_name: 'btc_mining_db_container'
    volumes:
        - ./data:/data
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=btc_mining_db'
  btc_mining_command:
    image: 'mainul35/btc-mining-command:1.0'
    container_name: 'btc-mining-command'
    ports:
      - '8081:8081'
    depends_on:
      - axonserver
    command: mvn clean spring-boot:run
    # Pass environment variables to the service
    environment:
      ACTIVE_PROFILE: docker
      AXON_AXONSERVER_SERVERS: 'axonserver:8124'
  btc_mining_query:
    image: 'mainul35/btc-mining-query:1.0'
    container_name: 'btc-mining-query'
    ports:
      - '8082:8082'
    depends_on:
      - btc_mining_db
      - axonserver
    command: mvn clean spring-boot:run
    # Pass environment variables to the service
    environment:
      ACTIVE_PROFILE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://btc_mining_db:5432/btc_mining_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      AXON_AXONSERVER_SERVERS: 'axonserver:8124'
